services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=devops_test
            - DB_USERNAME=root
            - DB_PASSWORD=password
        depends_on:
            - mysql

    mysql:
        image: mariadb:10.6
        restart: unless-stopped
        tty: true
        ports:
            - "3307:3307"
        environment:
            MYSQL_DATABASE: devops_test
            MYSQL_USER: root
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - laravel

volumes:
    mysql_data:
