services:
    app:
        build:
            context: .
        container_name: laravel_devops
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - laravel
        environment:
            - APP_ENV=laravel_devops
            - DB_CONNECTION=mysql
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=devops_test
            - DB_USERNAME=root
            - DB_PASSWORD=password

    mysql:
        image: mariadb:10.6
        container_name: mysql
        restart: unless-stopped
        tty: true
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: devops_test
        ports:
            - "3306:3306"
        networks:
            - laravel
        volumes:
            - db_data:/var/lib/mysql

networks:
    laravel:
        driver: bridge

volumes:
    db_data:
        driver: local
