version: '3.8'

services:
    app:
        build:
            context: .
        container_name: laravel_devops
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - laravel
        environment:
            - APP_ENV=testing
            - DB_CONNECTION=mysql
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=devops_test
            - DB_USERNAME=root
            - DB_PASSWORD=password

#    mysql:
#        image: mariadb:10.6
#        restart: unless-stopped
#        tty: true
#        ports:
#            - "3306:3306"
#        environment:
#            MYSQL_DATABASE: devops_test
#            MYSQL_USER: root
#            MYSQL_PASSWORD: password
#            MYSQL_ROOT_PASSWORD: secret
#            SERVICE_TAGS: dev
#            SERVICE_NAME: mysql
#        networks:
#            - laravel

networks:
    laravel:
        driver: bridge

volumes:
    db_data:
        driver: local
