services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=devops_test
            - DB_USERNAME=root
            - DB_PASSWORD=password
        depends_on:
            - mysql

    mysql:
        image: mysql:8.0
        container_name: laravel_mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: devops_test
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
