services:
    web:
        build:
            context: ./
            dockerfile: ./.docker/php/Dockerfile.local
        ports:
            - ${APP_PORT:-8000}:8000
            - ${VITE_PORT:-5173}:${VITE_PORT:-5173}
        volumes:
            - ./:${WORKDIR}
            - ./vendor/:${WORKDIR}/vendor
        networks:
            - lara11-beta
        depends_on:
            - mysql
            - redis
            - minio
            - mailpit
    mysql:
        image: mysql/mysql-server:${MYSQL_VERSION:-8.0}
        ports:
            - ${FORWARD_DB_PORT:-3306}:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - ${DB_VOLUME_LOCAL:-./database/mysql-test-data}:/var/lib/mysql
        networks:
            - lara11-beta
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - -p${DB_PASSWORD}
            retries: 3
            timeout: 5s
    redis:
        image: redis:alpine
        ports:
            - ${FORWARD_REDIS_PORT:-6379}:6379
        volumes:
            - ${REDIS_VOLUME_LOCAL:-./database/redis-data}:/data
        networks:
            - lara11-beta
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    minio:
        image: minio/minio:latest
        ports:
            - ${FORWARD_MINIO_PORT:-9000}:9000
            - ${FORWARD_MINIO_CONSOLE_PORT:-8900}:8900
        environment:
            MINIO_ROOT_USER: ${MINIO_ROOT_USER:-sail}
            MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-password}
        volumes:
            - ${MINIO_VOLUME_LOCAL:-./storage/minio-data}:/data
        networks:
            - lara11-beta
        command: minio server /data/minio --console-address ":${FORWARD_MINIO_CONSOLE_PORT}"
        healthcheck:
            test:
                - CMD
                - curl
                - -f
                - http://localhost:${FORWARD_MINIO_PORT}/minio/health/live
            retries: 3
            timeout: 5s
    mailpit:
        image: axllent/mailpit:latest
        ports:
            - ${FORWARD_MAILPIT_PORT:-1025}:1025
            - ${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025
        volumes:
            - ${MP_VOLUME_LOCAL:-./storage/mail-data}:/data
        networks:
            - lara11-beta
networks:
    lara11-beta:
        driver: bridge
